name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Clone Theme Git Submodule
        run: |
          ./clone_submod.sh

      - name: Build site, Fail on WARN
        run: |
          if hugo --minify 2>&1 | grep WARN; then
            exit 1
          fi

      - name: Copy site to nginx static site directory
        run: |
          rsync -a public/* /var/www/hugo.lan/
